trigger:
- master

stages:
- stage: "Build"
  jobs:
  - job: "BuildApp"
    pool:
      name: Default

    variables:
      buildConfiguration: 'Release'

    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory)'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: "DeployStaging"
  dependsOn: "Build"
  jobs:
  - job:
    pool:
      name: Default
    steps:
#      - download: current
#        artifact: drop
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.DefaultWorkingDirectory)'
           
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'InlineServiceConnection'
          appType: 'webApp'
          WebAppName: 'InlineM-Staging'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- stage: "DeployProduction"
  dependsOn: "DeployStaging"
  jobs:
  - job:
    pool:
      name: Default
    steps:
#        - download: current
#          artifact: drop

      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.DefaultWorkingDirectory)'
  
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'InlineServiceConnection'
          appType: 'webApp'
          WebAppName: 'InlineM-Production'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
