trigger:
- master

# pool:
#   vmImage: 'windows-latest'

stages:
- stage: "BuildStage"
  jobs:
  - job: "BuildJob"
    pool:
      name: 'Default'

    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'ARMTemplate/'
        Contents: '**'
        TargetFolder: '$(build.artifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'


- stage: "Staging"
  dependsOn: "BuildStage"
  jobs:
  - deployment:
    pool:
      name: 'Default' 
    environment: 'Staging'
    strategy:
     runOnce:
       deploy:
        steps:
           - task: DownloadBuildArtifacts@1
             inputs:
               buildType: 'current'
               downloadType: 'single'
               artifactName: 'drop'
               downloadPath: '$(System.DefaultWorkingDirectory)'
          #  - task: replacetokens@5
          #    inputs:
          #      rootDirectory: '$(System.DefaultWorkingDirectory)'
          #      targetFiles: 'parameters.json'
          #      encoding: 'auto'
          #      tokenPattern: 'custom'
          #      tokenPrefix: '#'
          #      tokenSuffix: '#'
          #      writeBOM: true
          #      actionOnMissing: 'warn'
          #      keepToken: false
          #      actionOnNoFiles: 'continue'
          #      enableTransforms: false
          #      enableRecursion: false
          #      useLegacyPattern: false
          #      enableTelemetry: true
          